# Generated by Django 5.1.5 on 2025-03-11 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.BigIntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.CharField(blank=True, null=True)),
                ('kakao_email', models.CharField(default=None, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('full_address', models.CharField(blank=True, null=True)),
                ('address_detail', models.CharField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
