# Generated by Django 5.1.5 on 2025-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kakao_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('full_address', models.TextField()),
                ('address_detail', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics')),
            ],
        ),
    ]
