# Generated by Django 5.1.5 on 2025-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_uid_alter_user_address_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
