# Generated by Django 5.1.5 on 2025-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('industries', models.ManyToManyField(related_name='categories', to='industries.industry')),
            ],
        ),
    ]
