# Generated by Django 5.1.5 on 2025-03-11 05:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(default='B', max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('sales_status', models.CharField(choices=[('sold', 'Sold'), ('available', 'Available'), ('pending', 'Pending')], default='available', max_length=50, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='users.user')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='users.user')),
            ],
        ),
    ]
