# Generated by Django 5.1.5 on 2025-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_id_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
