# Generated by Django 5.1.5 on 2025-05-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_origin_url"),
        ("users", "0002_alter_user_kakao_id_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_seller",
                to="users.user",
            ),
        ),
    ]
