# Generated by Django 5.1.5 on 2025-05-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
        ("packages", "0001_initial"),
        ("users", "0002_alter_user_kakao_id_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_packages",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="industry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="industries.industry",
            ),
        ),
    ]
