# Generated by Django 5.1.5 on 2025-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='https://www.animaltoc.com/news/articleView.html?idxno=1409', null=True),
        ),
    ]
