# Generated by Django 5.1.5 on 2025-02-25 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_address_detail_alter_user_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="uid",
        ),
        migrations.AlterField(
            model_name="user",
            name="address_detail",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="kakao_email",
            field=models.CharField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.CharField(blank=True, null=True),
        ),
    ]
