# Generated by Django 5.1.5 on 2025-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold',
            field=models.CharField(default='selling', max_length=10),
        ),
    ]
