# Generated by Django 5.1.5 on 2025-02-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_category_remove_product_created_at_and_more"),
        ("users", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller",
                to="users.user",
            ),
        ),
    ]
