# Generated by Django 5.1.5 on 2025-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
