# Generated by Django 5.1.5 on 2025-02-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('industries', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.ManyToManyField(related_name='packages_categories', to='categories.category')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
                ('product_id', models.ManyToManyField(related_name='package_products', to='products.product')),
            ],
        ),
    ]
