# Generated by Django 5.1.5 on 2025-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="industry",
            new_name="industry_id",
        ),
    ]
