# Generated by Django 5.1.5 on 2025-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_industry_package_industry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
