# Generated by Django 5.1.5 on 2025-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("industries", "0002_industry_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="industry_id",
        ),
        migrations.AddField(
            model_name="category",
            name="industry_ids",
            field=models.ManyToManyField(
                related_name="categories", to="industries.industry"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
